config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks
  resources :links
  root to: 'bibles#home'

  get 'users/manage', to: 'users#manage', as: 'manage_users'

  get '/search', to: 'bibles#search', as: 'search_bible', constraints: lambda { |req| req.format == :json }

  devise_for :users

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :user_tracks

  get '*path', to: 'bibles#route_error'
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:references, :string, :string, :string, :string, :string, :boolean, :date, :integer)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :references %>
    <%= form.text_field :references, id: :link_references %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string, id: :link_string %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string, id: :link_string %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string, id: :link_string %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string, id: :link_string %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string, id: :link_string %>
  </div>

  <div class="field">
    <%= form.label :boolean %>
    <%= form.text_field :boolean, id: :link_boolean %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, id: :link_date %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer, id: :link_integer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th>References</th>
      <th>String</th>
      <th>String</th>
      <th>String</th>
      <th>String</th>
      <th>String</th>
      <th>Boolean</th>
      <th>Date</th>
      <th>Integer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.references %></td>
        <td><%= link.string %></td>
        <td><%= link.string %></td>
        <td><%= link.string %></td>
        <td><%= link.string %></td>
        <td><%= link.string %></td>
        <td><%= link.boolean %></td>
        <td><%= link.date %></td>
        <td><%= link.integer %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>References:</strong>
  <%= @link.references %>
</p>

<p>
  <strong>String:</strong>
  <%= @link.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @link.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @link.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @link.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @link.string %>
</p>

<p>
  <strong>Boolean:</strong>
  <%= @link.boolean %>
</p>

<p>
  <strong>Date:</strong>
  <%= @link.date %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @link.integer %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>