config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks
  resources :links
  root to: 'bibles#home'

  get 'users/manage', to: 'users#manage', as: 'manage_users'

  get '/search', to: 'bibles#search', as: 'search_bible', constraints: lambda { |req| req.format == :json }

  devise_for :users

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :user_tracks

  get '*path', to: 'bibles#route_error'
end

app/models/user_track.rb
class UserTrack < ApplicationRecord
  belongs_to :user

  validates_inclusion_of :role, in: %w( Guest Contributor Moderator Admin )

  ROLES = %i[guest contributor moderator admin]
  # for view forms <%= f.collection_select(:role, UserTrack::ROLES, :to_s, lambda{|i| i.to_s.humanize}) %>
end

app/controllers/user_tracks_controller.rb
class UserTracksController < ApplicationController
  before_action :set_user_track, only: [:show, :edit, :update, :destroy]

  # GET /user_tracks
  # GET /user_tracks.json
  def index
    @user_tracks = UserTrack.all
  end

  # GET /user_tracks/1
  # GET /user_tracks/1.json
  def show
  end

  # GET /user_tracks/new
  def new
    @user_track = UserTrack.new
  end

  # GET /user_tracks/1/edit
  def edit
  end

  # POST /user_tracks
  # POST /user_tracks.json
  def create
    @user_track = UserTrack.new(user_track_params)

    respond_to do |format|
      if @user_track.save
        format.html { redirect_to @user_track, notice: 'User tracking record was successfully created.' }
        format.json { render :show, status: :created, location: @user_track }
        @user = User.find(params[:user_id])
        @user.role = params(:role)
        @user.approved_at = Time.now
        @user.approved_by = current_user.id
        @user.save!
      else
        format.html { render :new,  alert: 'Unable to create the user tracking record'}
        format.json { render json: @user_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_tracks/1
  # PATCH/PUT /user_tracks/1.json
  def update
    respond_to do |format|
      if @user_track.update(user_track_params)
        format.html { redirect_to @user_track, notice: 'User tracking record was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_track }
        @user = User.find(params[:user_id])
        @user.role = params(:role)
        @user.approved_at = Time.now
        @user.approved_by = current_user.id
        @user.save!
      else
        format.html { render :edit,  alert: 'Unable to update the user tracking record' }
        format.json { render json: @user_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_tracks/1
  # DELETE /user_tracks/1.json
  def destroy
    @user_track.destroy
    respond_to do |format|
      format.html { redirect_to user_tracks_url, notice: 'User tracking record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_track
      @user_track = UserTrack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_track_params
      params.require(:user_track).permit(:user_id, :role)
    end
end

app/helpers/user_tracks_helper.rb
module UserTracksHelper
end

app/views/user_tracks/_form.html.erb
<%= form_with(model: user_track, local: true) do |form| %>
  <% if user_track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_track.errors.count, "error") %> prohibited this user_track from being saved:</h2>

      <ul>
      <% user_track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :user_track_user_id %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role, id: :user_track_role %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_tracks/edit.html.erb
<h1>Editing User Track</h1>

<%= render 'form', user_track: @user_track %>

<%= link_to 'Show', @user_track %> |
<%= link_to 'Back', user_tracks_path %>

app/views/user_tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Tracks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_tracks.each do |user_track| %>
      <tr>
        <td><%= user_track.user %></td>
        <td><%= user_track.role %></td>
        <td><%= link_to 'Show', user_track %></td>
        <td><%= link_to 'Edit', edit_user_track_path(user_track) %></td>
        <td><%= link_to 'Destroy', user_track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Track', new_user_track_path %>

app/views/user_tracks/new.html.erb
<h1>New User Track</h1>

<%= render 'form', user_track: @user_track %>

<%= link_to 'Back', user_tracks_path %>

app/views/user_tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_track.user %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user_track.role %>
</p>

<%= link_to 'Edit', edit_user_track_path(@user_track) %> |
<%= link_to 'Back', user_tracks_path %>